
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv


export default{
  datasource: {
    
    db: {
      url: process.env.DATABASE_URL
    }
  }
}

